version: '3.8'

services:
  linera-node:
    build:
      context: .
      dockerfile: Dockerfile.linera
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    volumes:
      - linera-data:/root/.config/linera
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_LINERA_NODE_URL=http://linera-node:8080
    depends_on:
      - linera-node
    restart: unless-stopped

volumes:
  linera-data:
